# Generated by Django 3.2.7 on 2022-09-19 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220703_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=99, default = "")),
                ('customer_name', models.CharField(max_length=99, default = "")),
                ('adress', models.CharField(max_length=99, default = "")),
                ('room_type', models.CharField(max_length=99, default = "")),
                ('room_name', models.CharField(max_length=99, default = "")),
                ('drawer_type', models.CharField(max_length=99, default = "")),
                ('assembly_method', models.CharField(max_length=99, default = "")),
                ('assembly_method_wood_drawer', models.CharField(max_length=99, default = "")),
                ('side_height', models.IntegerField(max_length=99)),
                ('side_align', models.CharField(max_length=99, default = "")),
                ('base_type', models.CharField(max_length=99, default = "")),
                ('base_height', models.CharField(max_length=99, default = "")),
                ('close_furniture_material', models.CharField(max_length=99, default = "")),
                ('inner_drawer_material', models.CharField(max_length=99, default = "")),
                ('base_material', models.CharField(max_length=99, default = "")),
                ('fridge_finishing', models.CharField(max_length=99, default = "")),
                ('front_type', models.CharField(max_length=99, default = "")),
                ('front_model', models.CharField(max_length=99, default = "")),
                ('front_material', models.CharField(max_length=99, default = "")),
                ('front_finish', models.CharField(max_length=99, default = "")),
                ('side_type', models.CharField(max_length=99, default = "")),
                ('side_model', models.CharField(max_length=99, default = "")),
                ('side_material', models.CharField(max_length=99, default = "")),
                ('side_finish', models.CharField(max_length=99, default = "")),
                ('rail', models.CharField(max_length=99, default = "")),
                ('spacing', models.CharField(max_length=99, default = "")),
                ('outer_drawer_type', models.CharField(max_length=99, default = "")),
                ('inner_drawer_type', models.CharField(max_length=99, default = "")),
                ('handle', models.CharField(max_length=99, default = "")),
                ('opening_mechanisms', models.CharField(max_length=99, default = "")),
                ('tone', models.CharField(max_length=99, default = "")),
                ('oven', models.CharField(max_length=99, default = "")),
                ('stove_top', models.CharField(max_length=99, default = "")),
                ('dishwasher', models.CharField(max_length=99, default = "")),
                ('microwave', models.CharField(max_length=99, default = "")),
                ('stove_ventilator', models.CharField(max_length=99, default = "")),
                ('fridge', models.CharField(max_length=99, default = "")),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.furniture')),
            ],
        ),
    ]
