# Generated by Django 3.2.7 on 2022-09-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customorder_furniture_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='closing',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='customorder',
            name='cornice',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='customorder',
            name='cornice_length',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='customorder',
            name='final_height',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='customorder',
            name='hanging_method',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='customorder',
            name='led',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='customorder',
            name='legs',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='customorder',
            name='marble_thickness',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='customorder',
            name='parquet',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='customorder',
            name='parquet_size',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='customorder',
            name='top_surfaces_thickness',
            field=models.CharField(default='', max_length=99),
        ),
        migrations.AddField(
            model_name='customorder',
            name='top_surfaces_type',
            field=models.CharField(default='', max_length=99),
        ),
    ]
