# Generated by Django 3.2.7 on 2022-09-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220919_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='side_height',
            field=models.CharField(max_length=99),
        ),
    ]
